In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8 # length of integers
batch_size = 4 # how many of blocks are running in parallel

cuda


In [2]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
vocabulary_size = len(chars)

In [3]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([72, 34, 48, 45,  1, 37, 55, 54, 44, 45, 58, 46, 61, 52,  1, 37, 49, 66,
        41, 58, 44,  1, 55, 46,  1, 29, 66,  0,  0, 42, 65,  1, 26,  8,  1, 20,
        58, 41, 54, 51,  1, 16, 41, 61, 53,  0,  0,  0, 34, 48, 49, 59,  1, 42,
        55, 55, 51,  1, 49, 59,  1, 44, 45, 44, 49, 43, 41, 60, 45, 44,  1, 60,
        55,  1, 53, 65,  1, 47, 55, 55, 44,  1, 46, 58, 49, 45, 54, 44,  1,  3,
         1, 43, 55, 53, 58, 41, 44, 45,  0, 27])


In [4]:
n = int(0.8 * len(data))
train_data = data[:n]
val_data = data[n:]
print(train_data)
print(val_data)

tensor([72, 34, 48,  ...,  8, 71,  0])
tensor([ 0, 70, 15,  ...,  0,  0,  0])


In [10]:

def get_batch(split):
    data = train_data if split == 'train' else val_data    
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)

    # stacking in batches
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size] for i in ix])
    x, y = x.to(device), y.to(device)
    return x,y

x, y = get_batch('train')

print('inputs:')
print(x)
print('targets:')
print(y)



tensor([124581,  36257,  57895,  73644])
inputs:
tensor([[53, 41, 54,  1, 63, 41, 59,  1],
        [49, 47, 48, 60,  1, 55, 46,  1],
        [45,  1, 26, 49, 55, 54,  8,  1],
        [58, 49, 45, 54, 44,  1, 60, 48]], device='cuda:0')
targets:
tensor([[41, 54,  1, 63, 41, 59,  1],
        [47, 48, 60,  1, 55, 46,  1],
        [ 1, 26, 49, 55, 54,  8,  1],
        [49, 45, 54, 44,  1, 60, 48]], device='cuda:0')


In [ ]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size)
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, index, targets):
        logits = self.token_embedding_table(index)

        return logits


In [11]:

x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is tensor ',context,' target is ',target)

when input is tensor  tensor([72])  target is  tensor(34)
when input is tensor  tensor([72, 34])  target is  tensor(48)
when input is tensor  tensor([72, 34, 48])  target is  tensor(45)
when input is tensor  tensor([72, 34, 48, 45])  target is  tensor(1)
when input is tensor  tensor([72, 34, 48, 45,  1])  target is  tensor(37)
when input is tensor  tensor([72, 34, 48, 45,  1, 37])  target is  tensor(55)
when input is tensor  tensor([72, 34, 48, 45,  1, 37, 55])  target is  tensor(54)
when input is tensor  tensor([72, 34, 48, 45,  1, 37, 55, 54])  target is  tensor(44)
